# Generated by Django 3.2.19 on 2023-05-09 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
